/* ================= PWA: service worker, updates, install ================= */
const IS_ARTIFACT=!!(window.claude&&typeof window.claude.use==='function');
let swReg=null,installPrompt=null;
function registerPWA(){if(IS_ARTIFACT||!('serviceWorker' in navigator)||!/^https?:$/.test(location.protocol))return;
  navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{swReg=reg;if(reg.waiting)S.ui.updateReady=true;reg.addEventListener('updatefound',()=>{const nw=reg.installing;if(!nw)return;nw.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller){S.ui.updateReady=true;render()}})});render()}).catch(e=>console.warn('sw',e));
  let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()})}
function applyUpdate(){if(swReg&&swReg.waiting){swReg.waiting.postMessage({type:'SKIP_WAITING'})}else location.reload()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;S.ui.canInstall=true;render()});
window.addEventListener('appinstalled',()=>{installPrompt=null;S.ui.canInstall=false;setUiPref('installed',true);render()});
async function promptInstall(){if(installPrompt){installPrompt.prompt();const r=await installPrompt.userChoice.catch(()=>null);installPrompt=null;S.ui.canInstall=false;render();return r}return null}
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)&&!window.MSStream;
const isStandalone=()=>window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
function pwaBannerHtml(){if(IS_ARTIFACT)return '';const parts=[];if(S.ui.updateReady)parts.push(`<div class="note good" style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><span>A new version of Plenty is ready.</span><button class="btn sm primary" data-action="pwa-update">Reload to update</button></div>`);
  if(!isStandalone()&&!uiPref('installDismissed')){if(S.ui.canInstall)parts.push(`<div class="note" style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><span>Install Plenty for a full-screen app that opens offline.</span><span class="actions"><button class="btn sm primary" data-action="pwa-install">Install Plenty</button><button class="btn sm ghost" data-action="pwa-dismiss">Not now</button></span></div>`);else if(isIOS())parts.push(`<div class="note" style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><span>On iPhone: tap Share, then “Add to Home Screen” to install Plenty.</span><button class="btn sm ghost" data-action="pwa-dismiss">Got it</button></div>`)}
  return parts.length?`<div style="display:flex;flex-direction:column;gap:8px;margin-bottom:14px">${parts.join('')}</div>`:''}
function pwaCardHtml(){if(IS_ARTIFACT)return '';return `<div class="card pad"><h3 style="margin-bottom:8px">App</h3><p class="small muted">${isStandalone()?'Plenty is installed and running as an app.':'Plenty can be installed on your phone or computer and works offline: the current plan and grocery list are always available.'}</p><div class="actions" style="margin-top:10px">${S.ui.canInstall?`<button class="btn primary" data-action="pwa-install">Install Plenty</button>`:isIOS()&&!isStandalone()?'<span class="small muted">iPhone: Share → Add to Home Screen.</span>':''}<button class="btn" data-action="pwa-check">Check for updates</button></div><p class="small faint" style="margin-top:8px">Version ${typeof PLENTY_VERSION!=='undefined'?PLENTY_VERSION:'dev'}${navigator.onLine===false?' · offline':''}</p></div>`}

/* ---- appearance: light by default; dark or follow-system are optional ---- */
function currentTheme(){const t=uiPref('theme');return t==='dark'||t==='system'?t:'light'}
function applyTheme(t){t=t==='dark'||t==='system'?t:'light';if(IS_ARTIFACT&&document.documentElement.getAttribute('data-theme')&&!uiPref('theme'))return;document.documentElement.setAttribute('data-theme',t);const m=document.querySelector('meta[name="theme-color"]');if(m)m.setAttribute('content',t==='dark'||(t==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches)?'#1D2019':'#FBF7EF')}
function setTheme(t){setUiPref('theme',t);applyTheme(t);render()}
function appearanceCardHtml(){const t=currentTheme();return `<div class="card pad"><h3 style="margin-bottom:8px">Appearance</h3><p class="small muted">Plenty is light by default. Dark mode uses the same olive, sand and lemon palette with readable contrast.</p><div class="checks" style="margin-top:10px">${[['light','Light'],['dark','Dark'],['system','Follow system']].map(([v,l])=>`<label><input type="radio" name="theme" value="${v}" data-theme-pick="${v}" ${t===v?'checked':''}>${l}</label>`).join('')}</div></div>`}
