// Migration script (v2.2): five primary tabs, Settings and secondary destinations in a utility group, floating
// "Ask Plenty" assistant, Weekly Check-in card on Home, Health tab retired (data and detail view kept), hash deep links.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
function patch(file, pairs) { const p = path.join(root, file); let s = fs.readFileSync(p, 'utf8'); for (const [a, b] of pairs) { if (!s.includes(a)) throw new Error(file + ' missing: ' + a.slice(0, 90)); s = s.replace(a, b); } fs.writeFileSync(p, s); }

/* ---- skeleton: floating assistant button and mobile utility button ---- */
patch('src/1-head.html', [["<div id=\"modal\"></div>", "<button id=\"utilbtn\" class=\"utilbtn\" aria-label=\"Profile and settings\" hidden>P</button>\n<button id=\"fab\" class=\"fab ai-only\" aria-label=\"Ask Plenty\" hidden></button>\n<div id=\"modal\"></div>"]]);

/* ---- nav model, rail, render hooks, hash deep links ---- */
patch('src/3-store-views.js', [
  ["const TABS=[['home','Home'],['plan','Plan'],['discover','Discover'],['recipes','Recipes'],['groceries','Groceries'],['items','Items'],['athome','At Home'],['coach','Coach'],['health','Health'],['settings','Settings']];\nconst MOBILE_MAIN=['home','plan','groceries','coach'];",
   "const TABS=[['home','Home'],['plan','Plan'],['discover','Recipes'],['groceries','Groceries'],['athome','At Home']];           // primary navigation\nconst SECONDARY=[['items','Regular items & pets'],['recipes','Recipe box list'],['health','Weekly Check-in'],['settings','Settings']]; // utility menu\nconst MOBILE_MAIN=TABS.map(t=>t[0]);\nconst ALL_TABS=['home','plan','discover','recipes','groceries','items','athome','health','coach','settings'];\nconst navKeyFor=tab=>tab==='recipes'?'discover':tab;"],
  ["  rail.innerHTML=`\n    <div class=\"brand\"><div class=\"mark\">P</div><div class=\"name\">Plenty</div></div>\n    ${TABS.map(([k,l])=>`<button class=\"tab ${S.ui.tab===k?'on':''} ${MOBILE_MAIN.includes(k)?'':'desk'}\" data-tab=\"${k}\">${ICONS[k==='athome'?'home2':k]}<span>${l}</span></button>`).join('')}\n    <button class=\"tab mob ${MOBILE_MAIN.includes(S.ui.tab)?'':'on'}\" data-action=\"more\">${ICONS.more}<span>More</span></button>\n    <div class=\"spacer\"></div>\n",
   "  const ub=document.getElementById('utilbtn');if(ub){ub.hidden=false;ub.textContent=(S.settings.profileName||'P').trim()[0].toUpperCase()}const fab=document.getElementById('fab');if(fab){fab.hidden=false;fab.innerHTML=ICONS.coach+'<span>Ask Plenty</span>'}\n  rail.innerHTML=`\n    <div class=\"brand\"><div class=\"mark\">P</div><div class=\"name\">Plenty</div></div>\n    <div class=\"navgroup\" role=\"navigation\" aria-label=\"Main\">${TABS.map(([k,l])=>`<button class=\"tab ${navKeyFor(S.ui.tab)===k?'on':''}\" data-tab=\"${k}\" aria-current=\"${navKeyFor(S.ui.tab)===k?'page':'false'}\">${ICONS[k==='athome'?'home2':k]}<span>${l}</span></button>`).join('')}</div>\n    <div class=\"spacer\"></div>\n    <div class=\"navgroup util\" role=\"navigation\" aria-label=\"More\">${SECONDARY.filter(([k])=>k!=='settings'&&k!=='recipes').map(([k,l])=>`<button class=\"tab sm ${S.ui.tab===k?'on':''}\" data-tab=\"${k}\">${ICONS[k==='health'?'health':k]}<span>${l}</span></button>`).join('')}<button class=\"tab ${S.ui.tab==='settings'?'on':''}\" data-tab=\"settings\" aria-current=\"${S.ui.tab==='settings'?'page':'false'}\">${ICONS.settings}<span>Settings</span></button></div>\n"],
  ["  document.querySelectorAll('.tab[data-tab]').forEach(t=>t.classList.toggle('on',t.dataset.tab===S.ui.tab));\n  const more=document.querySelector('.tab.mob');if(more)more.classList.toggle('on',!MOBILE_MAIN.includes(S.ui.tab));",
   "  document.querySelectorAll('.tab[data-tab]').forEach(t=>t.classList.toggle('on',t.dataset.tab===navKeyFor(S.ui.tab)||t.dataset.tab===S.ui.tab));\n  if(S.ui.mode==='app'){try{if(location.hash!=='#'+S.ui.tab)history.replaceState(null,'','#'+S.ui.tab)}catch(e){}}\n  if(S.ui.assistantOpen&&typeof renderAssistant==='function')renderAssistant();if(S.ui.checkinOpen&&typeof renderCheckinModal==='function')renderCheckinModal();"],
  ["  if(S.ui.mode==='onboarding'){m.innerHTML=viewOnboarding();window.scrollTo(0,0);return}if(S.ui.mode==='pick'){m.innerHTML=viewProfilePick();return}",
   "  const ub=document.getElementById('utilbtn'),fb=document.getElementById('fab');if(ub)ub.hidden=S.ui.mode!=='app';if(fb)fb.hidden=S.ui.mode!=='app';\n  if(S.ui.mode==='onboarding'){m.innerHTML=viewOnboarding();window.scrollTo(0,0);return}if(S.ui.mode==='pick'){m.innerHTML=viewProfilePick();return}"],
  // boot: deep link from the hash
  ["async function boot(){\n  if(typeof applyTheme==='function')applyTheme(currentTheme());", "async function boot(){\n  if(typeof applyTheme==='function')applyTheme(currentTheme());\n  try{const h=location.hash.replace('#','');if(ALL_TABS.includes(h))S.ui.tab=h}catch(e){}\n  window.addEventListener('hashchange',()=>{const h=location.hash.replace('#','');if(ALL_TABS.includes(h)&&h!==S.ui.tab&&S.ui.mode==='app'){S.ui.tab=h;renderNav();render()}});"],
  // Home header + card + plan header
  ["<button class=\"btn primary ai-only\" data-action=\"tab\" data-tab=\"coach\">${ICONS.spark} Ask the coach</button></div></div>", "<button class=\"btn primary ai-only\" data-action=\"assistant\">${ICONS.spark} Ask Plenty</button></div></div>"],
  ["    ${healthHomeCard()}\n    ${checkinCard()}\n", "    ${weeklyCheckinCardHtml()}\n"],
  ["<button class=\"btn ai-only\" data-action=\"tab\" data-tab=\"coach\">${ICONS.spark} Plan with the coach</button></div></div>", "<button class=\"btn ai-only\" data-action=\"assistant\" data-draft=\"Plan my week within budget with breakfast, lunch, dinner and snacks.\">${ICONS.spark} Ask Plenty</button></div></div>"],
]);

/* ---- assistant: rename, safety notices, modal panel shared with the page view ---- */
{
  const p = path.join(root, 'src/4-views2.js'); let s = fs.readFileSync(p, 'utf8');
  const a = s.indexOf('function viewCoach(){'); const b = s.indexOf('/* ================= Settings ================= */');
  if (a < 0 || b < 0) throw new Error('viewCoach markers');
  const body = `const ASSISTANT_NOTICE='Plenty provides general planning and informational support, not medical, nutritional or financial advice.';
const HEALTH_NOTICE='Health insights are general guidance based on the information you enter. Plenty does not diagnose conditions or replace advice from a qualified healthcare professional.';
const HEALTH_WORDS=/\\b(health|healthy|calor|diet|cholesterol|nutrition|nutrient|protein|fiber|fibre|weight|symptom|pain|blood|sugar|allerg|medic|vitamin|heart|dizz|nause|fever)/i;
function assistantMessagesHtml(){const c=chat();return c.turns.length?c.turns.map((t,i)=>t.role==='user'?\`<div class="msg user">\${esc(t.content)}</div>\`:\`<div class="msg ai">\${fmtReply(t.content)}\${(t.actions||[]).length?\`<div class="props"><div class="eyebrow">\${t.applied?'Applied changes':'Proposed changes'}</div>\${t.actions.map((a,j)=>{const chk=validateAction(a);return \`<label class="prop \${chk.ok?'':'blocked'}"><input type="checkbox" data-turn="\${i}" data-j="\${j}" \${t.applied?'disabled '+(t.results&&t.results[j]&&t.results[j].ok?'checked':''):chk.ok?'checked':'disabled'}><span>\${esc(describeAction(a))}\${!chk.ok?\`<br><span class="why">\${esc(chk.why)}</span>\`:t.applied&&t.results&&t.results[j]&&!t.results[j].ok?\`<br><span class="why">\${esc(t.results[j].why||'Not applied')}</span>\`:''}</span></label>\`}).join('')}\${t.applied?'':\`<div class="actions" style="margin-top:8px"><button class="btn sm primary" data-action="apply-turn" data-turn="\${i}">Apply selected</button><button class="btn sm ghost" data-action="dismiss-turn" data-turn="\${i}">Dismiss</button></div>\`}</div>\`:''}\${HEALTH_WORDS.test(t.content)?\`<div class="small faint" style="margin-top:8px;border-top:1px solid var(--line);padding-top:6px">\${HEALTH_NOTICE}</div>\`:''}</div>\`).join('')
    :\`<div class="msg ai"><p>Hi. I can see this week's plan, your recipe box, regular items, \${esc(petName())}'s supplies, what is at home and the budget. Ask me to build the whole week, trim it to budget, swap meals, or tell me what you already have.</p><p class="small muted">I never remove essential food or \${esc(petName())}'s essentials to solve a budget problem. Budget, nutrition and price figures are estimates until a receipt confirms them.</p></div>\`}
function assistantComposerHtml(){return \`<div class="ai-block" style="display:block"><div class="composer"><textarea id="chatIn" rows="1" aria-label="Message Ask Plenty" placeholder="e.g. I already have six eggs and half a loaf. \${esc(petName())} needs food this week. Keep \${esc(S.settings.currency||'$')}5 free." data-input="chat">\${esc(S.ui.chatDraft)}</textarea><button class="btn primary icon" style="width:46px;height:46px;border-radius:12px" data-action="send" aria-label="Send" \${S.ui.busy?'disabled':''}>\${ICONS.send}</button></div><div class="small faint" style="margin-top:6px">\${ASSISTANT_NOTICE}</div></div>\`}
function assistantBodyHtml(){const c=chat();return \`\${sampleFn?\`<div class="quick">\${QUICK.map(q=>\`<button class="btn sm" data-action="quick" data-q="\${esc(q)}">\${esc(q)}</button>\`).join('')}</div>\`:''}
    <div class="msgs">\${assistantMessagesHtml()}\${S.ui.busy?\`<div class="thinking"><span class="sp"></span>Thinking about your week…</div>\`:''}</div>
    \${sampleFn?assistantComposerHtml():\`<div class="note">Ask Plenty needs an AI service, which this version does not include. Planning, grocery, budget, receipt and check-in features work without it.</div><div class="small faint" style="margin-top:6px">\${ASSISTANT_NOTICE}</div>\`}\`}
function viewCoach(){const c=chat();const B=budgetSummary();
  return \`<div class="head"><div>\${weekHead('Ask Plenty')}<div class="sub">Talks about the whole grocery week: meals, staples, snacks, \${esc(petName())}, household and budget. It proposes changes; you apply them and Plenty recalculates.</div></div>
    <div class="actions">\${c.turns.length?\`<button class="btn ghost" data-action="clear-chat">Clear conversation</button>\`:''}</div></div>
  <div class="chat"><div>\${assistantBodyHtml()}</div>
  <aside class="side"><div class="card"><div class="eyebrow">Week at a glance</div>
    <div class="kv"><span>Budget</span><b class="num">\${money(B.budget)}</b></div><div class="kv"><span>Estimated checkout</span><b class="num">\${money(B.actual)}</b></div><div class="kv"><span>Buffer</span><b class="num">\${money(B.buffer)}</b></div><div class="kv total"><span>\${B.remaining>=0?'Remaining':'Over'}</span><b class="num" style="color:\${B.remaining>=0?'var(--good)':'var(--bad)'}">\${money(Math.abs(B.remaining))}</b></div>
    <div class="kv"><span>Available for recipes</span><b class="num">\${money(B.availableForMeals)}</b></div><div class="kv"><span>Recipes cost</span><b class="num">\${money(B.groups.meals.actual)}</b></div><div class="kv"><span>\${esc(petName())} this week</span><b class="num">\${money(B.groups.pet.actual)}</b></div></div>
  <div class="card"><div class="eyebrow">Things you can say</div><ul class="small muted" style="margin:8px 0 0;padding-left:16px;display:flex;flex-direction:column;gap:4px"><li>"I already have tea, rice and olive oil."</li><li>"\${esc(petName())} needs a new bag of food this week."</li><li>"Keep 5 free in case I need something later."</li><li>"I want fruit every day."</li><li>"I'm shopping at Aldi this week."</li><li>"Use the frozen chicken first."</li></ul></div></aside></div>\`}
/* floating panel: same conversation, same state, opened from the chat button or Home */
function openAssistant(draft){if(draft&&!S.ui.chatDraft)S.ui.chatDraft=draft;S.ui.assistantOpen=true;renderAssistant();const ta=document.querySelector('.modal #chatIn');if(ta)ta.focus()}
function renderAssistant(){const c=chat();const box=document.getElementById('modal');const scroll=box.querySelector('.modal .msgs')?box.querySelector('.modal .msgs').scrollTop:null;
  box.innerHTML=\`<div class="overlay"><div class="modal chatpanel" role="dialog" aria-modal="true" aria-label="Ask Plenty"><div class="mh"><div><h2>Ask Plenty</h2><div class="small muted" style="margin-top:3px">Week of \${fmtDate(parseISO(S.ui.weekKey))} · proposals are applied only when you confirm</div></div><span class="actions">\${c.turns.length?\`<button class="btn sm ghost" data-action="clear-chat">Clear</button>\`:''}<button class="btn icon ghost" data-action="assistant-close" aria-label="Close">\${ICONS.x}</button></span></div><div class="mb" style="gap:10px">\${assistantBodyHtml()}</div></div></div>\`;
  const m=box.querySelector('.modal .msgs');if(m)m.scrollTop=scroll==null?m.scrollHeight:scroll}
function closeAssistant(){S.ui.assistantOpen=false;closeModal()}

`;
  s = s.slice(0, a) + body + s.slice(b);
  s = s.replace('/* ================= Coach ================= */', '/* ================= Ask Plenty (assistant) ================= */');
  s = s.replace("<label for=\"sDiet\">Food preferences for the coach</label>", "<label for=\"sDiet\">Food preferences for Ask Plenty</label>");
  s = s.replace("<p class=\"small muted\">Used when Claude plans your week or generates recipes.</p>", "<p class=\"small muted\">Used when Ask Plenty plans your week or drafts recipes.</p>");
  // Settings: Health preferences (profile + daily targets grouped)
  s = s.replace("<div class=\"card pad\"><h3 style=\"margin-bottom:12px\">Health profile</h3><p class=\"small muted\">Optional. Age, sex, height, weight, activity, goals, preferences and considerations, used only to word the Weekly Health Check and the coach's food suggestions. Weight loss is never assumed. Delete it at any time.</p><div class=\"actions\" style=\"margin-top:12px\"><button class=\"btn\" data-action=\"health-profile\">${hasHealthProfile()?'Edit health profile':'Add health profile'}</button><button class=\"btn ghost\" data-action=\"tab\" data-tab=\"health\">Open Weekly Health Check</button></div></div>",
    "<div class=\"card pad\"><h3 style=\"margin-bottom:12px\">Health preferences</h3><p class=\"small muted\">Optional. Age, sex, height, weight, activity, goals, preferences and considerations, used only to word the Weekly Check-in and Ask Plenty's food suggestions. Weight loss is never assumed. Delete it at any time.</p><div class=\"actions\" style=\"margin-top:12px\"><button class=\"btn\" data-action=\"health-profile\">${hasHealthProfile()?'Edit health preferences':'Add health preferences'}</button><button class=\"btn ghost\" data-action=\"tab\" data-tab=\"health\">Open Weekly Check-in</button></div><p class=\"small faint\" style=\"margin-top:10px\">${DISCLAIMER}</p></div>");
  if (!s.includes('Health preferences</h3>')) throw new Error('settings health card');
  s = s.replace("<h3 style=\"margin-bottom:12px\">Your daily targets</h3>", "<h3 style=\"margin-bottom:12px\">Daily targets & food preferences</h3>");
  fs.writeFileSync(p, s);
}

/* ---- health: Weekly Check-in card on Home, detail view renamed with back link ---- */
patch('src/11-health-ui.js', [
  ["function healthHomeCard(){", `function weeklyCheckinCardHtml(){const hc=healthCheck();const d=iso(today());const c=checkins();const todayDone=!!c.days[d]&&Object.keys(c.days[d]).length>1;const rep=reportedSummary();const obs=hc.positives[0]||hc.improvements[0]||'';
  return \`<div class="card pad"><div style="display:flex;justify-content:space-between;align-items:baseline;gap:8px"><h3>Weekly Check-in</h3><span class="chip \${todayDone?'good':''}">\${todayDone?'Today done':'Today open'}</span></div>
  <p class="muted" style="margin:6px 0 8px">\${esc(hc.summary)}</p>
  <div class="small muted">\${rep.days} check-in\${rep.days===1?'':'s'} this week\${rep.days?\`, vegetables or fruit on \${rep.veg}\`:''}.</div>
  \${obs?\`<div class="note good" style="margin-top:10px">\${esc(obs)}</div>\`:''}
  <div class="actions" style="margin-top:12px"><button class="btn primary" data-action="checkin-open">\${todayDone?'View today\\'s check-in':'Complete today\\'s check-in'}</button><button class="btn ghost" data-action="tab" data-tab="health">View details</button></div>
  <div class="small faint" style="margin-top:8px">Based on your plan, list and confirmed receipts. Purchases are not treated as eaten.</div></div>\`}
function renderCheckinModal(){const box=document.getElementById('modal');box.innerHTML=\`<div class="overlay"><div class="modal narrow" role="dialog" aria-modal="true" aria-label="Today's check-in">\${mhead("Today's check-in",'Optional. Five quick taps, no calories.')}<div class="mb">\${checkinCard().replace('<div class="card pad">','<div>')||'<div class="note">Skipped for today.</div>'}</div><div class="mf"><span></span><div class="actions"><button class="btn" data-action="checkin-close">Done</button></div></div></div></div>\`}
function healthHomeCard(){`],
  ["  return `<div class=\"head\"><div>${weekHead('Weekly Health Check')}<div class=\"sub\">${esc(hc.summary)}</div></div><div class=\"actions\"><button class=\"btn\" data-action=\"health-profile\">${hasHealthProfile(p)?'Edit health profile':'Add a health profile'}</button><button class=\"btn primary ai-only\" data-action=\"health-ask\">${ICONS.spark} Ask the coach</button></div></div>",
   "  return `<div class=\"head\"><div><button class=\"btn sm ghost\" data-action=\"tab\" data-tab=\"home\" style=\"margin-bottom:6px;padding-left:4px\">${ICONS.left} Home</button>${weekHead('Weekly Check-in')}<div class=\"sub\">${esc(hc.summary)}</div></div><div class=\"actions\"><button class=\"btn\" data-action=\"health-profile\">${hasHealthProfile(p)?'Edit health preferences':'Add health preferences'}</button><button class=\"btn primary ai-only\" data-action=\"health-ask\">${ICONS.spark} Ask Plenty</button></div></div>"],
  ["function openHealthProfile(){const p=clone(healthProfile());\n  openModal(`${mhead('Health profile',", "function openHealthProfile(){const p=clone(healthProfile());\n  openModal(`${mhead('Health preferences',"],
]);

/* ---- rules: rename and safety ---- */
patch('src/6-coach.js', [
  ["const COACH_RULES=()=>`You are Plenty's grocery coach for one household.", "const COACH_RULES=()=>`You are Ask Plenty, the planning assistant inside the Plenty app, for one household. You are not a coach, nutritionist, dietitian or financial advisor and never claim to be."],
  ["Quantities and money are estimates; the app recalculates the real totals after changes are applied.", "Quantities, prices, budget figures and nutrition values are ESTIMATES until a receipt or source confirms them; say so when they matter and never present an estimate as a confirmed fact.\nSAFETY: never diagnose a condition; never give medication advice or comment on medication changes; never suggest extreme calorie restriction, fasting for weight loss or other unsafe weight-loss methods; if the user describes potentially serious symptoms (for example chest pain, trouble breathing, fainting, severe allergic reaction, signs of an eating disorder), stop planning and recommend contacting a qualified healthcare professional or urgent care right away. Health remarks are general guidance based only on what the user entered."],
]);

/* ---- more menu, actions, inputs ---- */
patch('src/5-modals.js', [["function openMore(){openModal(`${mhead('More')}<div class=\"mb picker\">${TABS.filter(([k])=>!MOBILE_MAIN.includes(k)).map(([k,l])=>`<button class=\"pick plain\" data-action=\"tab\" data-tab=\"${k}\">${ICONS[k==='athome'?'home2':k]}<span class=\"rn\">${l}</span></button>`).join('')}</div>`,'narrow')}",
  "function openMore(){const name=S.settings.profileName||'Your profile';openModal(`${mhead(esc(name),S.ui.storage==='device'?'Saved privately on this device':'')}<div class=\"mb picker\">${SECONDARY.map(([k,l])=>`<button class=\"pick plain\" data-action=\"tab\" data-tab=\"${k}\">${ICONS[k==='health'?'health':k]}<span class=\"rn\">${l}</span></button>`).join('')}<button class=\"pick plain ai-only\" style=\"display:flex\" data-action=\"assistant\">${ICONS.coach}<span class=\"rn\">Ask Plenty</span></button></div></div>`,'narrow')}"]]);
patch('src/7-events-starter.js', [
  ["    case 'health-ask':S.ui.chatDraft='Am I eating reasonably balanced this week? Give me at most three practical changes that fit my budget.';S.ui.tab='coach';renderNav();render();break;", "    case 'health-ask':openAssistant('Am I eating reasonably balanced this week? Give me at most three practical changes that fit my budget.');break;\n    case 'assistant':closeModal();openAssistant(d.draft||'');break;\n    case 'assistant-close':closeAssistant();break;\n    case 'checkin-open':S.ui.checkinOpen=true;renderCheckinModal();break;\n    case 'checkin-close':S.ui.checkinOpen=false;closeModal();break;"],
  ["    case 'ask-coach':{const r=getRecipe(d.id);closeModal();S.ui.chatDraft=r?`About \"${r.name}\": does it fit this week's budget and plan? Where would you put it, and what should I swap out?`:'';S.ui.tab='coach';renderNav();render();break}", "    case 'ask-coach':{const r=getRecipe(d.id);closeModal();openAssistant(r?`About \"${r.name}\": does it fit this week's budget and plan? Where would you put it, and what should I swap out?`:'');break}"],
  ["    case 'send':{const ta=document.getElementById('chatIn');if(ta)sendChat(ta.value);break}", "    case 'send':{const ta=document.querySelector('.modal #chatIn')||document.getElementById('chatIn');if(ta)sendChat(ta.value);break}"],
  ["    case 'quick':S.ui.chatDraft=d.q;render();{const ta=document.getElementById('chatIn');if(ta){ta.focus();ta.style.height='auto';ta.style.height=Math.min(160,ta.scrollHeight)+'px'}}break;", "    case 'quick':S.ui.chatDraft=d.q;render();{const ta=document.querySelector('.modal #chatIn')||document.getElementById('chatIn');if(ta){ta.focus();ta.style.height='auto';ta.style.height=Math.min(160,ta.scrollHeight)+'px'}}break;"],
  ["document.getElementById('modal').addEventListener('click',e=>{if(e.target.matches('.overlay')||e.target.closest('[data-close]')){closeModal();return}const b=e.target.closest('[data-action]');if(b)handleAction(b,e)});", "document.getElementById('modal').addEventListener('click',e=>{if(e.target.matches('.overlay')||e.target.closest('[data-close]')){if(S.ui.assistantOpen)S.ui.assistantOpen=false;if(S.ui.checkinOpen)S.ui.checkinOpen=false;closeModal();return}const b=e.target.closest('[data-action]');if(b)handleAction(b,e)});\ndocument.getElementById('modal').addEventListener('input',e=>{if(e.target.dataset.input==='chat'){S.ui.chatDraft=e.target.value;e.target.style.height='auto';e.target.style.height=Math.min(160,e.target.scrollHeight)+'px'}});\ndocument.getElementById('fab').addEventListener('click',()=>openAssistant(''));\ndocument.getElementById('utilbtn').addEventListener('click',()=>openMore());"],
  ["document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalOpen())closeModal();", "document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalOpen()){S.ui.assistantOpen=false;S.ui.checkinOpen=false;closeModal()}"],
  ["    case 'checkin':{const date=iso(today());const c=checkins();const a={...(c.days[date]||{})};a[d.k]=d.v==='1';saveCheckin(date,a);render();break}", "    case 'checkin':{const date=iso(today());const c=checkins();const a={...(c.days[date]||{})};a[d.k]=d.v==='1';saveCheckin(date,a);render();if(S.ui.checkinOpen)renderCheckinModal();break}"],
  ["    case 'checkin-dismiss':dismissCheckin(d.date);render();toast('Skipped for today');break;", "    case 'checkin-dismiss':dismissCheckin(d.date);S.ui.checkinOpen=false;closeModal();render();toast('Skipped for today');break;"],
]);
// discover detail button label
patch('src/9-discover-ui.js', [["data-action=\"ask-coach\" data-id=\"${esc(id)}\">Ask the coach<", "data-action=\"ask-coach\" data-id=\"${esc(id)}\">Ask Plenty<"]]);
// health-ask inside settings quick prompts text unchanged; recipe ranking comment fine
console.log('wired nav');
