/* ================= Backup, restore, data controls, prototype migration ================= */
const BACKUP_FORMAT='plenty-backup';
const BACKUP_VERSION=2;
const b64=u8=>{let s='';for(let i=0;i<u8.length;i+=0x8000)s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000));return btoa(s)};
const unb64=s=>{const bin=atob(s);const u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u};
async function blobToBase64(blob){if(!blob)return '';if(typeof blob.arrayBuffer==='function')return b64(new Uint8Array(await blob.arrayBuffer()));return ''}
function containsSensitive(docs){return Object.keys(docs).some(p=>p==='app/health'||p==='app/checkins'||(p.startsWith('weeks/')&&docs[p]&&(docs[p].trips||[]).length))}
async function buildBackup(profileId){const pid=profileId||Store.profileId;const prof=Store.registry.profiles.find(p=>p.id===pid)||{name:'Me'};const docs=await Store.allDocs(pid);const blobs={};for(const m of await Store.listBlobs(pid)){const rec=await Store.getBlob(m.id,pid);if(rec&&rec.blob)blobs[m.id]={type:rec.type,data:await blobToBase64(rec.blob),tripId:rec.tripId||null}}
  return {format:BACKUP_FORMAT,version:BACKUP_VERSION,dataVersion:PLENTY_DATA_VERSION,exportedAt:new Date().toISOString(),app:'Plenty',profile:{name:prof.name},counts:backupCounts(docs,blobs),docs,blobs}}
function backupCounts(docs,blobs){const c=k=>Object.keys(docs).filter(p=>p.startsWith(k+'/')).length;return {recipes:c('recipes'),items:c('items'),inventory:c('inventory'),weeks:c('weeks'),prices:c('prices'),chats:c('chat'),receipts:Object.keys(docs).filter(p=>p.startsWith('weeks/')).reduce((a,p)=>a+((docs[p]||{}).trips||[]).length,0),images:Object.keys(blobs||{}).length,health:docs['app/health']?1:0,checkins:docs['app/checkins']?Object.keys(docs['app/checkins'].days||{}).length:0,settings:docs['app/settings']?1:0}}
/* encryption: AES-GCM with a PBKDF2-derived key */
const subtle=()=>(globalThis.crypto&&globalThis.crypto.subtle)||null;
async function deriveKey(password,salt,iterations){const enc=new TextEncoder();const km=await subtle().importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return subtle().deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},km,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptString(plain,password){const salt=crypto.getRandomValues(new Uint8Array(16));const iv=crypto.getRandomValues(new Uint8Array(12));const iterations=210000;const key=await deriveKey(password,salt,iterations);const ct=await subtle().encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(plain));return {format:BACKUP_FORMAT,version:BACKUP_VERSION,encrypted:true,kdf:'PBKDF2-SHA256',iterations,cipher:'AES-GCM',salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(ct))}}
async function decryptEnvelope(env,password){const key=await deriveKey(password,unb64(env.salt),env.iterations||210000);const pt=await subtle().decrypt({name:'AES-GCM',iv:unb64(env.iv)},key,unb64(env.data));return new TextDecoder().decode(pt)}
async function serializeBackup(backup,password){if(password){const env=await encryptString(JSON.stringify(backup),password);env.exportedAt=backup.exportedAt;env.profile={name:backup.profile.name};env.counts=backup.counts;return JSON.stringify(env)}return JSON.stringify(backup)}
async function parseBackup(text,password){let obj;try{obj=JSON.parse(String(text))}catch(e){return {ok:false,error:'This file is not a Plenty backup (not valid JSON).'}}
  if(!obj||obj.format!==BACKUP_FORMAT)return {ok:false,error:'This file is not a Plenty backup.'};
  if(obj.encrypted){if(!password)return {ok:false,needsPassword:true,summary:{name:obj.profile&&obj.profile.name,exportedAt:obj.exportedAt,counts:obj.counts},error:'This backup is encrypted. Enter its password.'};try{obj=JSON.parse(await decryptEnvelope(obj,password))}catch(e){return {ok:false,needsPassword:true,error:'Wrong password, or the file is damaged.'}}}
  return validateBackup(obj)}
function validateBackup(obj){const errors=[];if(!obj||obj.format!==BACKUP_FORMAT)errors.push('Not a Plenty backup.');if(typeof obj.version!=='number'||obj.version<1)errors.push('Missing backup version.');if(obj.version>BACKUP_VERSION)errors.push(`This backup was made by a newer Plenty (version ${obj.version}). Update the app first.`);if(!obj.docs||typeof obj.docs!=='object'||Array.isArray(obj.docs))errors.push('The backup has no documents.');
  if(!errors.length){for(const p in obj.docs){if(!/^[A-Za-z0-9_\-.~:@+]+(\/[A-Za-z0-9_\-.~:@+]+)+$/.test(p)){errors.push('Damaged document path: '+p.slice(0,40));break}if(obj.docs[p]!==null&&(typeof obj.docs[p]!=='object'||Array.isArray(obj.docs[p]))){errors.push('Damaged document: '+p.slice(0,40));break}}}
  if(errors.length)return {ok:false,error:errors.join(' ')};
  const docs={};const from=obj.dataVersion||obj.version||1;for(const p in obj.docs){const d=migrateDoc(p,obj.docs[p],from);if(d!==null)docs[p]=d}
  return {ok:true,backup:{...obj,docs,blobs:obj.blobs||{}},summary:{name:(obj.profile&&obj.profile.name)||'Unknown',exportedAt:obj.exportedAt||'',counts:backupCounts(docs,obj.blobs||{}),migrated:from<PLENTY_DATA_VERSION}}}
async function applyBackup(profileId,backup,mode){const pid=profileId;if(mode==='replace')await Store.clearProfile(pid);for(const p in backup.docs)await Store.set(p,backup.docs[p],pid);
  for(const id in backup.blobs||{}){const b=backup.blobs[id];if(!b||!b.data)continue;const bytes=unb64(b.data);const blob=typeof Blob!=='undefined'?new Blob([bytes],{type:b.type||'image/jpeg'}):{size:bytes.length,type:b.type,arrayBuffer:async()=>bytes.buffer};await Store.putBlob(id,blob,{tripId:b.tripId||null,type:b.type},pid)}
  return verifyImport(pid,backup)}
async function verifyImport(profileId,backup){const docs=await Store.allDocs(profileId);const missing=Object.keys(backup.docs).filter(p=>!(p in docs));const blobs=await Store.listBlobs(profileId);const missingBlobs=Object.keys(backup.blobs||{}).filter(id=>!blobs.some(b=>b.id===id));return {ok:!missing.length&&!missingBlobs.length,docs:Object.keys(docs).length,expectedDocs:Object.keys(backup.docs).length,blobs:blobs.length,missing,missingBlobs}}
function downloadText(filename,text,type){if(typeof document==='undefined')return false;try{const blob=new Blob([text],{type:type||'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},2000);return true}catch(e){return false}}
const backupFilename=name=>`plenty-backup-${String(name||'profile').toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${iso(today())}.json`;

/* ---- UI ---- */
async function openExport(){if(db){toast('Inside Claude, your data lives in the artifact. Use the standalone Plenty for backups.');return}const backup=await buildBackup();const sensitive=containsSensitive(backup.docs)||Object.keys(backup.blobs).length>0;const c=backup.counts;
  openModal(`${mhead('Export a backup','One file with everything in this profile. Keep it somewhere safe; it is how you move Plenty to another device.')}<div class="mb">
    <div class="card pad"><div class="kv"><span>Profile</span><b>${esc(backup.profile.name)}</b></div><div class="kv"><span>Recipes · items · inventory</span><b class="num">${c.recipes} · ${c.items} · ${c.inventory}</b></div><div class="kv"><span>Weeks · receipts · images</span><b class="num">${c.weeks} · ${c.receipts} · ${c.images}</b></div><div class="kv"><span>Health profile · check-ins</span><b class="num">${c.health?'yes':'no'} · ${c.checkins}</b></div></div>
    ${sensitive?`<label class="checks" style="display:flex"><input type="checkbox" id="bxEnc" checked> Encrypt with a password (recommended: this backup contains health or receipt information)</label><div class="row"><div class="field"><label for="bxPw">Password</label><input id="bxPw" type="password" autocomplete="new-password"></div><div class="field"><label for="bxPw2">Repeat</label><input id="bxPw2" type="password" autocomplete="new-password"></div></div><div class="small faint">There is no recovery if you forget it. Plenty never stores the password.</div>`:'<div class="small faint">This backup has no health or receipt data, so encryption is optional.</div><label class="checks" style="display:flex"><input type="checkbox" id="bxEnc"> Encrypt with a password</label><div class="row"><div class="field"><label for="bxPw">Password</label><input id="bxPw" type="password"></div><div class="field"><label for="bxPw2">Repeat</label><input id="bxPw2" type="password"></div></div>'}
    <div id="bxOut"></div></div>
    <div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn primary" id="bxGo">Download backup</button></div></div>`);
  document.getElementById('bxGo').onclick=async()=>{const enc=document.getElementById('bxEnc').checked;const pw=document.getElementById('bxPw').value;const pw2=document.getElementById('bxPw2').value;const out=document.getElementById('bxOut');if(enc){if(pw.length<8){out.innerHTML='<div class="note bad">Use at least 8 characters.</div>';return}if(pw!==pw2){out.innerHTML='<div class="note bad">The passwords do not match.</div>';return}}
    out.innerHTML='<div class="thinking"><span class="sp"></span>Preparing…</div>';const text=await serializeBackup(backup,enc?pw:null);const ok=downloadText(backupFilename(backup.profile.name),text);
    if(ok){closeModal();toast('Backup downloaded')}else out.innerHTML=`<div class="note">Your browser blocked the download. Copy the text below into a file named ${esc(backupFilename(backup.profile.name))}.</div><textarea style="min-height:160px;width:100%;${fieldCss}" readonly>${esc(text)}</textarea>`}}
function openImport(){if(db){toast('Import is available in the standalone Plenty.');return}let parsed=null,fileText='';
  openModal(`${mhead('Import a backup','Nothing changes until you confirm. Existing information is only replaced if you choose that.')}<div class="mb">
    <input type="file" id="biFile" accept="application/json,.json" style="${fieldCss}">
    <div id="biPw" hidden><div class="field"><label for="biPass">Backup password</label><input id="biPass" type="password"></div></div>
    <div id="biOut"></div></div>
    <div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn" id="biCheck" disabled>Check backup</button></div></div>`);
  const fi=document.getElementById('biFile');fi.onchange=()=>{const f=fi.files[0];document.getElementById('biCheck').disabled=!f;if(f)f.text().then(t=>{fileText=t})};
  document.getElementById('biCheck').onclick=async()=>{const out=document.getElementById('biOut');const pw=document.getElementById('biPass').value;const res=await parseBackup(fileText,pw||null);
    if(!res.ok){if(res.needsPassword)document.getElementById('biPw').hidden=false;out.innerHTML=`<div class="note ${res.needsPassword&&!pw?'':'bad'}">${esc(res.error)}</div>`;return}
    parsed=res;const s=res.summary,c=s.counts;const cur=await Store.allDocs();const hasCurrent=Object.keys(cur).length>0;
    out.innerHTML=`<div class="card pad"><div class="kv"><span>Profile in backup</span><b>${esc(s.name)}</b></div><div class="kv"><span>Exported</span><b>${esc(s.exportedAt?s.exportedAt.slice(0,16).replace('T',' '):'unknown')}</b></div><div class="kv"><span>Will import</span><b class="num">${c.recipes} recipes, ${c.items} items, ${c.inventory} inventory, ${c.weeks} weeks (${c.receipts} receipts, ${c.images} images), ${c.health?'a health profile':'no health profile'}, ${c.checkins} check-ins</b></div>${s.migrated?'<div class="small muted">The backup is from an older Plenty and will be migrated to the current format.</div>':''}</div>
      ${hasCurrent?`<div class="note warn" style="margin-top:10px"><b>This profile already has information.</b> Choose whether the backup replaces it or is added to it. Replacing removes everything currently in this profile first.</div><div class="checks" style="margin-top:8px"><label><input type="radio" name="biMode" value="merge" checked> Add to current data (documents with the same id are overwritten)</label><label><input type="radio" name="biMode" value="replace"> Replace current data</label><label><input type="radio" name="biMode" value="new"> Import into a new profile named “${esc(s.name)}”</label></div>`:'<div class="small muted" style="margin-top:8px">This profile is empty, so the backup is imported as it is.</div>'}
      <div class="actions" style="margin-top:12px"><button class="btn primary" id="biGo">Import now</button></div>`;
    document.getElementById('biGo').onclick=async()=>{const modeEl=document.querySelector('input[name="biMode"]:checked');const mode=modeEl?modeEl.value:'merge';const go=async()=>{let pid=Store.profileId;if(mode==='new'){pid=await Store.createProfile(s.name,{activate:false})}const v=await applyBackup(pid,parsed.backup,mode==='replace'?'replace':'merge');if(mode==='new')await Store.switchProfile(pid);await loadProfileState();S.ui.mode='app';closeModal();renderNav();render();toast(v.ok?`Backup imported: ${v.docs} documents, ${v.blobs} images verified.`:`Imported with ${v.missing.length+v.missingBlobs.length} problem(s). Check your data.`)};
      if(mode==='replace')confirmModal('Replace everything in this profile?','All current plans, recipes, receipts, pets and health data in this profile are removed and replaced by the backup. Export a backup first if you are unsure.','Replace and import',go,true);else go()}}}
function dataControlsHtml(){if(db)return '';const wk=week();const trips=(wk.trips||[]).length;const allTrips=Object.values(S.weeks).reduce((a,w)=>a+((w.trips||[]).length),0);
  return `<div class="card pad"><h3 style="margin-bottom:8px">Your data</h3><p class="small muted">${PRIVACY_TEXT}</p>
    <div class="actions" style="margin-top:12px"><button class="btn primary" data-action="backup-export">Export a backup</button><button class="btn" data-action="backup-import">Import a backup</button></div>
    <div class="eyebrow" style="margin:16px 0 6px">Remove information</div>
    <div class="actions"><button class="btn" data-action="health-profile">Edit or delete health profile</button><button class="btn" data-action="tab" data-tab="home" title="Receipts are listed on Home; each one has a delete button">Receipts (${trips} this week)</button><button class="btn" data-action="delete-history" ${allTrips?'':'disabled'}>Delete shopping history (${allTrips})</button><button class="btn" data-action="clear-week">Reset the current week</button><button class="btn danger" data-action="delete-all">Delete all Plenty data</button></div>
    <p class="small faint" style="margin-top:8px">Receipt photos are kept only on this device inside Plenty's local database and are removed together with their receipt, or with the shopping history.</p></div>`}
function openPrototypeMigration(det){openModal(`${mhead('Earlier Plenty data found','From the prototype that stored data in this browser.')}<div class="mb"><div class="card pad"><div class="kv"><span>Recipes</span><b class="num">${det.recipes}</b></div><div class="kv"><span>Weeks</span><b class="num">${det.weeks}</b></div><div class="kv"><span>Regular items</span><b class="num">${det.items}</b></div><div class="kv"><span>Health profile</span><b>${det.hasHealth?'yes':'no'}</b></div><div class="kv"><span>Receipts</span><b>${det.hasReceipts?'yes':'no'}</b></div></div>
    <p class="small muted">Migrating copies this into your new profile's local database, after saving a backup file of the old data. The old data stays in the browser until you confirm it can go.</p><div id="pmOut"></div></div>
    <div class="mf"><button class="btn ghost" data-close>Not now</button><div class="actions"><button class="btn primary" id="pmGo">Back up and migrate</button></div></div>`);
  document.getElementById('pmGo').onclick=async()=>{const out=document.getElementById('pmOut');out.innerHTML='<div class="thinking"><span class="sp"></span>Saving a backup of the old data…</div>';
    const old={format:BACKUP_FORMAT,version:BACKUP_VERSION,dataVersion:1,exportedAt:new Date().toISOString(),app:'Plenty prototype',profile:{name:'prototype'},counts:backupCounts(det.docs,{}),docs:det.docs,blobs:{}};downloadText('plenty-prototype-backup-'+iso(today())+'.json',JSON.stringify(old));
    const n=await importPrototypeData(det,Store.profileId);const cur=await Store.allDocs();const okAll=Object.keys(det.docs).every(p=>p in cur);await loadProfileState();render();
    out.innerHTML=`<div class="note ${okAll?'good':'bad'}">${okAll?`${n} documents imported and verified.`:'Some documents could not be verified; the old data is untouched.'}</div>${okAll?'<div class="actions" style="margin-top:8px"><button class="btn" id="pmKeep">Keep old data too</button><button class="btn primary" id="pmRemove">Remove old browser data</button></div>':''}`;
    if(okAll){document.getElementById('pmKeep').onclick=()=>{markPrototypeMigrated();closeModal()};document.getElementById('pmRemove').onclick=()=>{removePrototypeLocalData();markPrototypeMigrated();closeModal();toast('Old browser data removed')}}}}
async function deleteAllPlentyData(){const pid=Store.profileId;await Store.deleteProfile(pid);S.recipes={};S.items={};S.inventory={};S.weeks={};S.chats={};S.prices={};S.history={viewed:[],cooked:[]};S.health=null;S.checkins=null;S.settings={...DEFAULT_SETTINGS};S.loaded=false;S.ui.mode=Store.registry.profiles.length?'pick':'onboarding';S.ui.ob={step:0,a:{...S.ui.ob.a,name:'',pets:[]}};renderNav();render()}
