/* ================= Accounts (Netlify Identity + Functions) =================
   Local data stays authoritative. The account is a private copy the user fills and reads on purpose.
   Active only when the page was built with PLENTY_CLOUD=netlify (a <meta name="plenty-cloud"> tag is present). */
const CLOUD=(()=>{const m=document.querySelector('meta[name="plenty-cloud"]');return m?m.content:''})();
S.cloud={user:null,ready:false,profile:null,busy:false,unavailable:''};
const cloudOn=()=>CLOUD==='netlify'&&!IS_ARTIFACT;
function initAccount(){if(!cloudOn())return;const w=window.netlifyIdentity;if(!w){S.cloud.unavailable='The sign-in service did not load. Check your connection and reload.';return}
  w.on('init',u=>{S.cloud.user=u||null;S.cloud.ready=true;render();if(u)loadCloudProfile()});
  w.on('login',u=>{S.cloud.user=u;w.close();render();loadCloudProfile();toast(`Signed in as ${u.email}`)});
  w.on('logout',()=>{S.cloud.user=null;S.cloud.profile=null;render();toast('Signed out')});
  w.on('error',e=>{console.warn('identity',e&&e.message);S.cloud.unavailable=''});
  w.init({APIUrl:location.origin+'/.netlify/identity'})}
if(cloudOn()){if(window.netlifyIdentity)initAccount();else window.addEventListener('load',initAccount)}
async function cloudToken(){const u=S.cloud.user;if(!u)throw {code:'unauthenticated'};return u.jwt()}
async function api(path,opts){opts=opts||{};const token=await cloudToken();const res=await fetch('/api/'+path,{method:opts.method||'GET',headers:{Authorization:'Bearer '+token,...(opts.body?{'Content-Type':'application/json'}:{})},body:opts.body?JSON.stringify(opts.body):undefined});
  if(opts.raw)return res;let j=null;try{j=await res.json()}catch(e){}if(!res.ok){const err=(j&&j.error)||{code:'http_'+res.status,message:'The account service answered '+res.status+'.'};err.status=res.status;err.details=(j&&j.error&&j.error.details)||null;throw err}return j}
async function loadCloudProfile(){try{S.cloud.profile=await api('profile');S.cloud.unavailable=''}catch(e){S.cloud.profile=null;S.cloud.unavailable=e.code==='database_not_configured'?'The account database is not enabled on this deployment yet. Sign-in works, but nothing can be stored until the site owner enables Netlify Database.':(e.message||'Could not reach the account service.')}render()}
const cloudErr=e=>e&&e.code==='unauthenticated'?'Sign in first.':(e&&e.message)||'The account service could not be reached.';

/* ---- Settings card ---- */
function accountCardHtml(){if(!cloudOn())return '';const u=S.cloud.user;const p=S.cloud.profile;const imported=p&&(p.imports||[]).some(i=>i.source_profile_id===Store.profileId);
  if(!u)return `<div class="card pad"><h3 style="margin-bottom:8px">Account <span class="faint small" style="font-family:var(--body)">optional</span></h3><p class="small muted">Plenty works fully on this device without an account. An account adds a private copy of your data on the server so you can restore it on another device, and private storage for receipt photos. Nothing syncs automatically yet.</p>${S.cloud.unavailable?`<div class="note warn" style="margin-top:10px">${esc(S.cloud.unavailable)}</div>`:''}<div class="actions" style="margin-top:12px"><button class="btn primary" data-action="acct-login" ${S.cloud.ready||window.netlifyIdentity?'':'disabled'}>Sign in or create account</button></div><p class="small faint" style="margin-top:8px">Email verification, password recovery and password changes are handled in the sign-in dialog.</p></div>`;
  const c=(p&&p.counts)||{};
  return `<div class="card pad"><h3 style="margin-bottom:8px">Account</h3><div class="kv"><span>Signed in as</span><b style="overflow-wrap:anywhere">${esc(u.email||'')}</b></div>${p?`<div class="kv"><span>In your account</span><b class="num">${c.recipes||0} recipes · ${c.weekly_plans||0} weeks · ${c.receipts||0} receipts · ${c.health_profiles?'health profile':'no health data'}</b></div><div class="kv"><span>This local profile</span><b>${imported?'imported before':'not imported yet'}</b></div>`:S.cloud.unavailable?`<div class="note warn" style="margin-top:8px">${esc(S.cloud.unavailable)}</div>`:'<div class="thinking"><span class="sp"></span>Loading account…</div>'}
    <div class="note" style="margin-top:10px">${esc(PRIVACY_TEXT)} Your account holds a copy only when you import; restoring on another device is a manual step. Automatic synchronization between devices is not available yet.</div>
    <div class="actions" style="margin-top:12px"><button class="btn primary" data-action="acct-import" ${p?'':'disabled'}>Import this profile into my account</button><button class="btn" data-action="acct-restore" ${p?'':'disabled'}>Restore from my account</button><button class="btn" data-action="acct-export" ${p?'':'disabled'}>Export account data</button><button class="btn" data-action="acct-manage">Password &amp; email</button><button class="btn ghost" data-action="acct-logout">Sign out</button></div>
    <div class="eyebrow" style="margin:14px 0 6px">Remove from account</div><div class="actions"><button class="btn" data-action="acct-delete-health" ${p?'':'disabled'}>Delete health data</button><button class="btn" data-action="acct-delete-prices" ${p?'':'disabled'}>Delete price history</button><button class="btn danger" data-action="acct-delete">Delete account and all its data</button></div></div>`}

/* ---- import local profile into the account (preview -> confirm) ---- */
async function openAccountImport(){if(!S.cloud.user)return;const backup=await buildBackup();const body={sourceProfileId:Store.profileId,exportedAt:backup.exportedAt,docs:backup.docs};
  openModal(`${mhead('Import this profile into your account','A private copy on the server. Local data on this device stays exactly as it is.')}<div class="mb" id="aiBody"><div class="thinking"><span class="sp"></span>Checking your account…</div></div><div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn primary" id="aiGo" disabled>Import</button></div></div>`);
  let preview;try{preview=(await api('app-data?preview=1',{method:'POST',body})).preview}catch(e){document.getElementById('aiBody').innerHTML=`<div class="note bad">${esc(cloudErr(e))}</div>`;return}
  const c=backup.counts;document.getElementById('aiBody').innerHTML=`<div class="card pad"><div class="kv"><span>Local profile</span><b>${esc(backup.profile.name)}</b></div><div class="kv"><span>Will send</span><b class="num">${c.recipes} recipes, ${c.items} items, ${c.inventory} inventory, ${c.weeks} weeks (${c.receipts} receipts), ${c.health?'a health profile':'no health data'}, ${c.checkins} check-ins</b></div><div class="kv"><span>Already in account</span><b class="num">${preview.accountDocCount} documents</b></div></div>
    ${preview.alreadyImported?`<div class="note warn" style="margin-top:10px">This profile was imported before (${esc(String(preview.previousImport.importedAt||'').slice(0,16).replace('T',' '))}). Importing again overwrites documents with the same ids in the account.</div>`:''}
    ${preview.accountDocCount&&!preview.alreadyImported?'<div class="note" style="margin-top:10px">Your account already has data from another profile or device. Merge adds this profile\'s documents to it; replace removes the account copy first.</div>':''}
    <div class="checks" style="margin-top:10px"><label><input type="radio" name="aiMode" value="merge" checked> Merge into account</label><label><input type="radio" name="aiMode" value="replace"> Replace account copy</label></div>
    ${c.health?'<div class="small faint" style="margin-top:8px">Health data is stored in separate tables and can be deleted from the account on its own.</div>':''}<div id="aiOut"></div>`;
  const go=document.getElementById('aiGo');go.disabled=false;go.onclick=async()=>{const mode=document.querySelector('input[name="aiMode"]:checked').value;go.disabled=true;document.getElementById('aiOut').innerHTML='<div class="thinking"><span class="sp"></span>Importing…</div>';
    try{const res=await api('app-data',{method:'POST',body:{...body,mode,force:preview.alreadyImported}});closeModal();await loadCloudProfile();toast(`${res.imported} documents stored in your account`)}
    catch(e){go.disabled=false;document.getElementById('aiOut').innerHTML=`<div class="note bad">${esc(cloudErr(e))}</div>`}}}
/* ---- restore account copy into a new local profile ---- */
async function openAccountRestore(){if(!S.cloud.user)return;openModal(`${mhead('Restore from your account','Creates a new local profile from the account copy. Existing local profiles are not touched.')}<div class="mb" id="arBody"><div class="thinking"><span class="sp"></span>Fetching…</div></div><div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn primary" id="arGo" disabled>Restore into a new profile</button></div></div>`);
  let data;try{data=await api('app-data')}catch(e){document.getElementById('arBody').innerHTML=`<div class="note bad">${esc(cloudErr(e))}</div>`;return}
  const parsed=validateBackup({format:BACKUP_FORMAT,version:BACKUP_VERSION,dataVersion:PLENTY_DATA_VERSION,exportedAt:new Date().toISOString(),profile:{name:(data.docs['app/settings']||{}).profileName||S.cloud.user.email},docs:data.docs,blobs:{}});
  if(!parsed.ok){document.getElementById('arBody').innerHTML=`<div class="note bad">${esc(parsed.error)}</div>`;return}const s=parsed.summary.counts;
  document.getElementById('arBody').innerHTML=`<div class="card pad"><div class="kv"><span>Account copy</span><b class="num">${s.recipes} recipes, ${s.items} items, ${s.inventory} inventory, ${s.weeks} weeks (${s.receipts} receipts), ${s.health?'a health profile':'no health data'}</b></div><div class="kv"><span>Receipt photos in account</span><b class="num">${(data.receipts||[]).filter(r=>r.image).length}</b></div></div><div class="small muted" style="margin-top:8px">Receipt photos stay in the account and can be viewed from each receipt; they are not copied to this device.</div><div id="arOut"></div>`;
  const go=document.getElementById('arGo');go.disabled=!Object.keys(data.docs).length;go.onclick=async()=>{go.disabled=true;const pid=await Store.createProfile(parsed.summary.name,{activate:false});const v=await applyBackup(pid,parsed.backup,'replace');await Store.switchProfile(pid);await loadProfileState();S.ui.mode='app';S.ui.tab='home';closeModal();renderNav();render();toast(v.ok?`Restored ${v.docs} documents into a new profile`:'Restored with some problems; check your data')}}
async function accountExportDownload(){try{const res=await api('account-export',{raw:true});if(!res.ok)throw {message:'Export failed ('+res.status+').'};const text=await res.text();downloadText('plenty-account-export-'+iso(today())+'.json',text)||openModal(`${mhead('Account export')}<div class="mb"><textarea readonly style="min-height:200px;width:100%;${fieldCss}">${esc(text)}</textarea></div><div class="mf"><button class="btn" data-close>Done</button></div>`);toast('Account export downloaded')}catch(e){toast(cloudErr(e))}}
function openAccountDelete(){openModal(`${mhead('Delete your account?','Removes everything the account holds: settings, plans, recipes, receipts and their photos, price history, health data, and the login itself. Local data on this device is not affected.')}<div class="mb"><div class="field"><label for="adConfirm">Type DELETE to confirm</label><input id="adConfirm" autocomplete="off"></div><div id="adOut"></div></div><div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn danger" id="adGo">Delete account</button></div></div>`,'narrow');
  document.getElementById('adGo').onclick=async()=>{if(document.getElementById('adConfirm').value.trim()!=='DELETE'){document.getElementById('adOut').innerHTML='<div class="note bad">Type DELETE exactly to confirm.</div>';return}document.getElementById('adGo').disabled=true;
    try{const r=await api('account-delete',{method:'DELETE',body:{confirm:'DELETE'}});closeModal();toast(r.note||'Account deleted');if(window.netlifyIdentity)window.netlifyIdentity.logout()}catch(e){document.getElementById('adGo').disabled=false;document.getElementById('adOut').innerHTML=`<div class="note bad">${esc(cloudErr(e))}</div>`}}}

/* ---- receipt photos in the account ---- */
async function uploadTripPhotoToAccount(tripId){if(!S.cloud.user){toast('Sign in first.');return}for(const k in S.weeks){const tr=(S.weeks[k].trips||[]).find(t=>t.id===tripId);if(!tr)continue;const rec=tr.imageId?await Store.getBlob(tr.imageId):null;if(!rec||!rec.blob){toast('This receipt has no photo on this device.');return}
    try{let remoteId=tr.remoteReceiptId;if(!remoteId){const created=await api('receipts',{method:'POST',body:{localTripId:tr.id,weekStart:k,date:tr.date,store:tr.store||'',total:tr.amount,tax:tr.tax||0,discount:tr.discount||0,currency:S.settings.currency,note:tr.note||'',method:tr.method||'quick',lines:(tr.lines||[]).map(l=>({name:l.name,qty:l.qty,price:l.price,category:l.category,status:l.status,purpose:l.purpose,canon:l.canon,pet:!!l.pet}))}});remoteId=created.receipt.id}
      const b64=await blobToBase64(rec.blob);const up=await api('receipt-image',{method:'POST',body:{receiptId:remoteId,contentType:rec.type||rec.blob.type,data:b64}});tr.remoteReceiptId=remoteId;tr.remoteImage=true;tr.processingStatus=up.processing.status;writeDoc('weeks/'+k,S.weeks[k]);render();toast('Photo stored in your account. '+up.processing.message)}
    catch(e){toast(cloudErr(e))}return}}
async function removeTripPhotoFromAccount(tripId){for(const k in S.weeks){const tr=(S.weeks[k].trips||[]).find(t=>t.id===tripId);if(!tr||!tr.remoteReceiptId)continue;try{await api('receipt-image?id='+encodeURIComponent(tr.remoteReceiptId),{method:'DELETE'});tr.remoteImage=false;writeDoc('weeks/'+k,S.weeks[k]);render();toast('Photo removed from your account')}catch(e){toast(cloudErr(e))}return}}
function accountPhotoControlsHtml(tr){if(!cloudOn()||!S.cloud.user)return '';return tr.remoteImage?`<div class="note" style="margin-top:8px;display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;align-items:center"><span>Stored in your account · <b>processing not connected yet</b> (line items stay manual)</span><button class="btn sm ghost" data-action="acct-photo-remove" data-id="${esc(tr.id)}">Remove from account</button></div>`:`<div class="actions" style="margin-top:8px"><button class="btn sm" data-action="acct-photo-upload" data-id="${esc(tr.id)}">Store photo in my account</button></div>`}

/* ---- sync interface: documented contract, manual mode in this phase (see docs/SYNC.md) ---- */
const SyncAdapter={mode:'manual',status(){return {mode:'manual',queued:0,note:'Local data is authoritative; import and restore are explicit actions.'}},enqueue(){return false},async flush(){return {pushed:0}},async pull(){return {pulled:0}}};
