/* ================= modals ================= */
const modalOpen=()=>!!document.querySelector('.overlay');
function openModal(html,cls){document.getElementById('modal').innerHTML=`<div class="overlay"><div class="modal ${cls||''}" role="dialog" aria-modal="true">${html}</div></div>`;const first=document.querySelector('.modal input:not([type=checkbox]),.modal textarea,.modal button');if(first)first.focus({preventScroll:true})}
function closeModal(){document.getElementById('modal').innerHTML=''}
const mhead=(title,sub)=>`<div class="mh"><div><h2>${title}</h2>${sub?`<div class="small muted" style="margin-top:3px">${sub}</div>`:''}</div><button class="btn icon ghost" data-close aria-label="Close">${ICONS.x}</button></div>`;
const fieldCss='padding:8px 10px;border:1px solid var(--line2);border-radius:var(--r-s);background:var(--surface);min-width:0;width:100%';
function confirmModal(title,body,label,onYes,danger){openModal(`${mhead(title)}<div class="mb"><div>${body}</div></div><div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn ${danger?'danger':'primary'}" id="cf">${label}</button></div></div>`,'narrow');document.getElementById('cf').onclick=()=>{closeModal();onYes()}}
function openMore(){openModal(`${mhead('More')}<div class="mb picker">${TABS.filter(([k])=>!MOBILE_MAIN.includes(k)).map(([k,l])=>`<button class="pick plain" data-action="tab" data-tab="${k}">${ICONS[k==='athome'?'home2':k]}<span class="rn">${l}</span></button>`).join('')}</div>`,'narrow')}

/* ---- recipe editor ---- */
function ingRow(i){i=i||{qty:'',unit:'g',name:'',category:'',price:''};return `<div class="ing-row"><input type="number" step="any" min="0" placeholder="Qty" value="${i.qty===0?'':esc(i.qty)}" data-f="qty" aria-label="Quantity"><select data-f="unit" aria-label="Unit">${UNITS.map(u=>`<option value="${u}" ${u===i.unit?'selected':''}>${u||'—'}</option>`).join('')}</select><input placeholder="Ingredient" value="${esc(i.name)}" data-f="name" aria-label="Ingredient"><select data-f="category" aria-label="Category"><option value="">Category (auto)</option>${CATS.map(a=>`<option ${a===(i.category||i.aisle)?'selected':''}>${a}</option>`).join('')}</select><input class="pr" type="number" step="0.01" min="0" placeholder="${esc(S.settings.currency)}" value="${i.price===0||i.price==null?'':esc(i.price)}" data-f="price" aria-label="Price for this quantity"><button class="x" type="button" data-rm aria-label="Remove">${ICONS.x}</button></div>`}
function openEditor(r,opts){opts=opts||{};const isNew=!r||!S.recipes[r.id];
  r=r?clone(r):{id:uid(),name:'',mealTypes:['dinner'],tags:[],minutes:30,servings:2,ingredients:[],steps:[],nutrition:null,notes:''};if(!r.id)r.id=uid();const n=r.nutrition||{};
  openModal(`${mhead(isNew?'New recipe':'Edit recipe',opts.sub||'Prices are for the quantity used, so the list can total correctly.')}
    <div class="mb" id="ed">${opts.notice?`<div class="note">${opts.notice}</div>`:''}
      <div class="field"><label for="eName">Name</label><input id="eName" value="${esc(r.name)}" required placeholder="e.g. Chickpea & spinach curry"></div>
      <div class="row"><div class="field"><label for="eMin">Minutes</label><input id="eMin" type="number" min="1" value="${r.minutes||''}"></div><div class="field"><label for="eServ">Makes servings</label><input id="eServ" type="number" min="1" value="${r.servings||1}"></div></div>
      <div class="field"><label>Good for</label><div class="tagrow" id="eMeals" style="margin:0">${MEAL_TYPES.map(m=>`<button type="button" class="tag pick ${(r.mealTypes||['dinner']).includes(m)?'on':''}" data-t="${m}">${MEAL_LABEL[m]}</button>`).join('')}</div></div>
      <div class="field"><label>Tags</label><div class="tagrow" id="eTags" style="margin:0">${TAGS.map(t=>`<button type="button" class="tag pick ${(r.tags||[]).includes(t)?'on':''}" data-t="${t}">${t}</button>`).join('')}</div></div>
      <div class="field"><label>Ingredients <span class="faint" style="font-weight:400">qty · unit · name · category · price for that qty</span></label><div class="ing-rows" id="eIngs">${(r.ingredients||[]).map(ingRow).join('')}</div><div><button type="button" class="btn sm" id="eAddIng">${ICONS.plus} Ingredient</button></div></div>
      <div class="field"><label for="eSteps">Method <span class="faint" style="font-weight:400">one step per line</span></label><textarea id="eSteps" style="min-height:110px">${esc((r.steps||[]).join('\n'))}</textarea></div>
      <div class="field"><label>Nutrition per serving <span class="faint" style="font-weight:400">optional</span></label><div class="row"><input id="eK" type="number" min="0" placeholder="kcal" value="${n.kcal||''}" aria-label="kcal" style="${fieldCss}"><input id="eP" type="number" min="0" placeholder="protein g" value="${n.protein||''}" aria-label="protein" style="${fieldCss}"><input id="eC" type="number" min="0" placeholder="carbs g" value="${n.carbs||''}" aria-label="carbs" style="${fieldCss}"><input id="eF" type="number" min="0" placeholder="fat g" value="${n.fat||''}" aria-label="fat" style="${fieldCss}"></div>
        <div style="margin-top:6px"><button type="button" class="btn sm ai-only" id="eEstimate">${ICONS.spark} Estimate nutrition, prices and categories</button></div><div id="eEstOut"></div></div>
      <div class="field"><label for="eNotes">Notes</label><input id="eNotes" value="${esc(r.notes||'')}" placeholder="Leftover tips, swaps, where you found it"></div></div>
    <div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn primary" id="eSave">${isNew?'Save recipe':'Save changes'}</button></div></div>`,'wide');
  const ings=document.getElementById('eIngs');if(!ings.children.length)ings.insertAdjacentHTML('beforeend',ingRow()+ingRow()+ingRow());
  document.getElementById('eAddIng').onclick=()=>{ings.insertAdjacentHTML('beforeend',ingRow());ings.lastElementChild.querySelector('input').focus()};
  ings.addEventListener('click',e=>{const b=e.target.closest('[data-rm]');if(b)b.closest('.ing-row').remove()});
  ings.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-f="price"]')){e.preventDefault();const row=e.target.closest('.ing-row');if(row===ings.lastElementChild)ings.insertAdjacentHTML('beforeend',ingRow());row.nextElementSibling.querySelector('input').focus()}});
  document.getElementById('eTags').addEventListener('click',e=>{const b=e.target.closest('[data-t]');if(b)b.classList.toggle('on')});
  document.getElementById('eMeals').addEventListener('click',e=>{const b=e.target.closest('[data-t]');if(b)b.classList.toggle('on')});
  const read=()=>{const rows=[...ings.querySelectorAll('.ing-row')].map(row=>{const g=f=>row.querySelector(`[data-f="${f}"]`).value;const name=g('name').trim();if(!name)return null;const pr=parseFloat(g('price'));return {qty:parseFloat(g('qty'))||0,unit:g('unit'),name,category:g('category')||guessCat(name),price:isNaN(pr)?0:pr}}).filter(Boolean);
    const num=id=>{const v=parseFloat(document.getElementById(id).value);return isNaN(v)?null:v};const k=num('eK'),p=num('eP'),c=num('eC'),f=num('eF');
    const mt=[...document.querySelectorAll('#eMeals .on')].map(b=>b.dataset.t);
    return {...r,name:document.getElementById('eName').value.trim(),minutes:num('eMin')||0,servings:Math.max(1,num('eServ')||1),mealTypes:mt.length?mt:['dinner'],tags:[...document.querySelectorAll('#eTags .on')].map(b=>b.dataset.t),ingredients:rows,steps:document.getElementById('eSteps').value.split('\n').map(s=>s.trim()).filter(Boolean),nutrition:(k||p||c||f)?{kcal:k||0,protein:p||0,carbs:c||0,fat:f||0}:null,notes:document.getElementById('eNotes').value.trim(),createdAt:r.createdAt||Date.now()}};
  document.getElementById('eSave').onclick=async()=>{const out=read();if(!out.name){toast('Give the recipe a name.');document.getElementById('eName').focus();return}if(!out.ingredients.length){toast('Add at least one ingredient.');return}delete out.costPerServing;closeModal();await saveRecipe(out);toast(isNew?'Recipe saved':'Changes saved');if(opts.then)opts.then(out)};
  const est=document.getElementById('eEstimate');if(est)est.onclick=async()=>{if(!sampleFn)return;const cur=read();if(!cur.ingredients.length){toast('Add ingredients first.');return}const out=document.getElementById('eEstOut');out.innerHTML='<div class="thinking"><span class="sp"></span>Estimating…</div>';est.disabled=true;
    try{const res=await sampleFn.json(`You are a nutritionist and supermarket price estimator. Recipe: ${cur.name||'untitled'}; makes ${cur.servings} servings. Ingredients for the whole recipe: ${cur.ingredients.map(i=>`${i.qty} ${i.unit} ${i.name}`).join('; ')}. Currency ${S.settings.currency}${S.settings.store?', shopping at '+S.settings.store:''}. Price means the cost of exactly the quantity used (pro-rata of a pack), not a whole pack.
Reply with only JSON: {"nutrition":{"kcal":number,"protein":number,"carbs":number,"fat":number} per single serving,"ingredients":[{"name":"<exactly as given>","price":number,"category":"<one of ${CATS.join(', ')}>"}]}`,{modelTier:'quick'});
      const nn=res&&res.nutrition||{};const set=(id,v)=>{document.getElementById(id).value=v==null||isNaN(v)?'':Math.round(v)};set('eK',+nn.kcal);set('eP',+nn.protein);set('eC',+nn.carbs);set('eF',+nn.fat);
      if(res&&Array.isArray(res.ingredients)){const by={};res.ingredients.forEach(x=>{by[String(x.name||'').trim().toLowerCase()]=x});[...ings.querySelectorAll('.ing-row')].forEach(row=>{const nm=row.querySelector('[data-f="name"]').value.trim().toLowerCase();const x=by[nm];if(!x)return;if(x.price!=null&&!isNaN(+x.price))row.querySelector('[data-f="price"]').value=(+x.price).toFixed(2);if(CATS.includes(x.category))row.querySelector('[data-f="category"]').value=x.category})}
      r.nutritionEstimated=true;out.innerHTML='<div class="small faint" style="margin-top:6px">Estimates filled in. Adjust anything that looks off.</div>'}
    catch(e){out.innerHTML=`<div class="note bad" style="margin-top:6px">${aiErr(e)}</div>`}finally{est.disabled=false}}}
function aiErr(e){const c=e&&e.code;if(c==='not_granted'||c==='sampling_disabled'||c==='not_declared'){document.documentElement.classList.remove('ai');return 'Claude is not available for this page.'}if(c==='rate_limited')return 'Claude is busy or you have hit your usage limit. Try again in a little while.';if(c==='invalid_json')return 'Claude answered in an unexpected format. Try again.';if(c==='cancelled')return 'Stopped.';if(c==='refused')return 'Claude could not help with that input. Try rephrasing.';if(c==='prompt_too_large')return 'Too much to send at once. Clear the conversation and try again.';return 'Something went wrong talking to Claude. Try again.'}

/* ---- item editor ---- */
function openItemEditor(it,kind){const isNew=!it;it=it?clone(it):{id:uid('i'),kind:kind||'grocery',name:'',category:kind==='pet'?'Pet':'Produce',qty:1,unit:'pcs',price:0,frequency:'weekly',brand:'',store:'',priority:kind==='pet'?'essential':'preferred',inStock:false,packageSize:'',packageUnit:'g',packagePrice:'',usePerDay:'',remaining:''};
  const isPet=it.kind==='pet';const multi=isMulti(it);
  openModal(`${mhead(isNew?(isPet?`New ${esc(petName())} item`:'New regular item'):'Edit item',isPet?`${esc(petName())}'s supplies stay separate from your own food and nutrition.`:'Lands on the grocery list when due and counts toward the same weekly budget.')}
    <div class="mb" id="ie">
      <div class="row"><div class="field" style="flex:2"><label for="iName">Item</label><input id="iName" value="${esc(it.name)}" placeholder="${isPet?'e.g. Dry dog food':'e.g. Bananas'}" required></div><div class="field"><label for="iKind">Type</label><select id="iKind"><option value="grocery" ${it.kind==='grocery'?'selected':''}>Grocery</option><option value="household" ${it.kind==='household'?'selected':''}>Household</option><option value="pet" ${isPet?'selected':''}>Pet</option></select></div>${pets().length>1?`<div class="field"><label for="iPet">Which pet</label><select id="iPet">${pets().map(p=>`<option value="${p.id}" ${(it.petId||(pets()[0]||{}).id)===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div>`:''}</div>
      <div class="row"><div class="field"><label for="iCat">Store category</label><select id="iCat">${CATS.map(c=>`<option ${c===it.category?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label for="iGroup">Budget group</label><select id="iGroup"><option value="">Auto</option>${GROUPS.filter(g=>g!=='meals').map(g=>`<option value="${g}" ${it.group===g?'selected':''}>${esc(GROUP_LABEL(g))}</option>`).join('')}</select></div></div>
      <div class="row"><div class="field"><label for="iPrio">Priority</label><select id="iPrio">${PRIOS.map(p=>`<option ${p===(it.priority||'preferred')?'selected':''}>${p}</option>`).join('')}</select></div><div class="field"><label for="iFreq">Frequency</label><select id="iFreq">${FREQS.map(([v,l])=>`<option value="${v}" ${v===(it.frequency||'weekly')?'selected':''}>${l}</option>`).join('')}</select></div></div>
      <div class="row"><div class="field"><label for="iBrand">Preferred brand</label><input id="iBrand" value="${esc(it.brand||'')}" placeholder="optional"></div><div class="field"><label for="iStore">Preferred store</label><input id="iStore" value="${esc(it.store||'')}" placeholder="${esc(S.settings.store||'optional')}"></div></div>
      <label class="checks" style="display:flex"><input type="checkbox" id="iMulti" ${multi?'checked':''}> Lasts several weeks (track package and daily use)</label>
      <div id="iSimple" ${multi?'hidden':''}><div class="row"><div class="field"><label for="iQty">Quantity per purchase</label><input id="iQty" type="number" step="any" min="0" value="${it.qty||''}"></div><div class="field"><label for="iUnit">Unit</label><select id="iUnit">${UNITS.map(u=>`<option value="${u}" ${u===(it.unit||'pcs')?'selected':''}>${u||'—'}</option>`).join('')}</select></div><div class="field"><label for="iPrice">Expected price (${esc(S.settings.currency)})</label><input id="iPrice" type="number" step="0.01" min="0" value="${it.price||''}"></div></div>
        <label class="checks" style="display:flex;margin-top:10px"><input type="checkbox" id="iStock" ${it.inStock?'checked':''}> Already in stock (skip until it runs out)</label></div>
      <div id="iMultiBox" ${multi?'':'hidden'}><div class="row"><div class="field"><label for="iPkg">Package size</label><input id="iPkg" type="number" step="any" min="0" value="${it.packageSize||''}" placeholder="e.g. 12"></div><div class="field"><label for="iPkgU">Unit</label><select id="iPkgU">${UNITS.map(u=>`<option value="${u}" ${u===(it.packageUnit||'kg')?'selected':''}>${u||'—'}</option>`).join('')}</select></div><div class="field"><label for="iPkgP">Package price (${esc(S.settings.currency)})</label><input id="iPkgP" type="number" step="0.01" min="0" value="${it.packagePrice||''}"></div></div>
        <div class="row" style="margin-top:8px"><div class="field"><label for="iUse">Used per day (same unit)</label><input id="iUse" type="number" step="any" min="0" value="${it.usePerDay||''}" placeholder="e.g. 0.3"></div><div class="field"><label for="iRem">Remaining now (same unit)</label><input id="iRem" type="number" step="any" min="0" value="${multi?Math.round(petStatus(it).remaining*100)/100:(it.remaining||'')}"></div></div>
        <div class="small muted" id="iCalc" style="margin-top:8px"></div></div>
    </div>
    <div class="mf">${isNew?'<span></span>':`<button class="btn ghost danger" id="iDel">Delete</button>`}<div class="actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="iSave">${isNew?'Add item':'Save'}</button></div></div>`);
  const $=id=>document.getElementById(id);
  const calc=()=>{const ps=parseFloat($('iPkg').value),up=parseFloat($('iUse').value),pp=parseFloat($('iPkgP').value)||0,rem=parseFloat($('iRem').value);if(!(ps>0&&up>0)){$('iCalc').textContent='Enter package size and daily use to see run-out and weekly cost.';return}const weeks=ps/up/7;const days=rem>=0?rem/up:null;$('iCalc').innerHTML=`One package lasts about <b>${Math.round(weeks*10)/10} weeks</b> · normalized <b>${money(pp/weeks)}</b> a week${days!=null?` · runs out around <b>${fmtDate(addDays(today(),Math.floor(days)))}</b>`:''}. In the week you buy it, checkout shows the full ${money(pp)}.`};
  $('iMulti').onchange=()=>{$('iSimple').hidden=$('iMulti').checked;$('iMultiBox').hidden=!$('iMulti').checked;calc()};['iPkg','iUse','iPkgP','iRem'].forEach(id=>$(id).oninput=calc);calc();
  $('iKind').onchange=()=>{if($('iKind').value==='pet'){$('iCat').value='Pet';$('iPrio').value='essential'}else if($('iKind').value==='household'&&$('iCat').value==='Pet')$('iCat').value='Household'};
  if($('iDel'))$('iDel').onclick=()=>{closeModal();confirmModal('Delete item?',`<b>${esc(it.name)}</b> will no longer appear on lists.`,'Delete',()=>{deleteItem(it.id);toast('Deleted')},true)};
  $('iSave').onclick=()=>{const name=$('iName').value.trim();if(!name){toast('Give the item a name.');return}const m=$('iMulti').checked;
    const out={...it,name,kind:$('iKind').value,category:$('iCat').value,group:$('iGroup').value||undefined,priority:$('iPrio').value,frequency:$('iFreq').value,petId:$('iPet')?$('iPet').value:(it.petId||(pets()[0]||{}).id||undefined),brand:$('iBrand').value.trim(),store:$('iStore').value.trim(),qty:parseFloat($('iQty').value)||1,unit:$('iUnit').value,price:parseFloat($('iPrice').value)||0,inStock:$('iStock').checked};
    if(m){out.packageSize=parseFloat($('iPkg').value)||0;out.packageUnit=$('iPkgU').value;out.packagePrice=parseFloat($('iPkgP').value)||0;out.usePerDay=parseFloat($('iUse').value)||0;out.remaining=parseFloat($('iRem').value)||0;out.remainingAsOf=iso(today());if(!(out.packageSize>0&&out.usePerDay>0)){toast('Package size and daily use are needed to track it.');return}}else{delete out.packageSize;delete out.usePerDay;delete out.packagePrice;delete out.remaining;delete out.remainingAsOf;delete out.packageUnit}
    if(!out.group)delete out.group;closeModal();saveItem(out);toast(isNew?'Item added':'Saved')}}

/* ---- inventory editor ---- */
function openInvEditor(v){const isNew=!v;v=v?clone(v):{id:uid('h'),name:'',qty:'',unit:'',location:'Pantry',note:''};
  openModal(`${mhead(isNew?'Add to At Home':'Edit At Home item','Leave quantity empty to mean you have enough.')}<div class="mb">
    <div class="field"><label for="hName">Item</label><input id="hName" value="${esc(v.name)}" placeholder="e.g. Eggs" required></div>
    <div class="row"><div class="field"><label for="hQty">Quantity</label><input id="hQty" type="number" step="any" min="0" value="${v.qty||''}" placeholder="—"></div><div class="field"><label for="hUnit">Unit</label><select id="hUnit">${UNITS.map(u=>`<option value="${u}" ${u===(v.unit||'')?'selected':''}>${u||'—'}</option>`).join('')}</select></div><div class="field"><label for="hLoc">Where</label><select id="hLoc">${LOCS.map(l=>`<option ${l===v.location?'selected':''}>${l}</option>`).join('')}</select></div></div>
    <div class="field"><label for="hNote">Note</label><input id="hNote" value="${esc(v.note||'')}" placeholder="e.g. use first, opened Monday"></div></div>
    <div class="mf">${isNew?'<span></span>':'<button class="btn ghost danger" id="hDel">Used up</button>'}<div class="actions"><button class="btn ghost" data-close>Cancel</button><button class="btn primary" id="hSave">${isNew?'Add':'Save'}</button></div></div>`,'narrow');
  const $=id=>document.getElementById(id);if($('hDel'))$('hDel').onclick=()=>{closeModal();deleteInv(v.id);toast('Removed from At Home')};
  $('hSave').onclick=()=>{const name=$('hName').value.trim();if(!name){toast('Name the item.');return}const q=parseFloat($('hQty').value);closeModal();saveInv({...v,name,qty:isNaN(q)?0:q,unit:$('hUnit').value,location:$('hLoc').value,note:$('hNote').value.trim()});toast(isNew?'Added to At Home':'Saved')}}

/* ---- slot picker ---- */
function openPicker(day,meal,add){const list=recipeList();const items=Object.values(S.items).filter(i=>i.kind!=='pet').sort((a,b)=>a.name.localeCompare(b.name));
  const cooked=planEntries().filter(e=>e.type==='recipe'&&(e.day<day||(e.day===day&&MEAL_TYPES.indexOf(e.meal)<MEAL_TYPES.indexOf(meal))));
  const draw=q=>{const ql=q.trim().toLowerCase();const fit=r=>(r.mealTypes||['dinner']).includes(meal);
    const rs=list.filter(r=>!ql||r.name.toLowerCase().includes(ql)||(r.tags||[]).some(t=>t.includes(ql))).sort((a,b)=>(fit(b)-fit(a))||(b.favorite?1:0)-(a.favorite?1:0));
    const is=items.filter(i=>!ql||i.name.toLowerCase().includes(ql));
    document.getElementById('pickList').innerHTML=`${cooked.length&&!ql?`<div class="eyebrow" style="margin:4px 0">Leftovers from</div>${[...new Map(cooked.map(e=>[e.recipe.id,e])).values()].map(e=>`<button class="pick" data-choose="l:${e.recipe.id}"><span class="rn" style="color:var(--warn)">Leftovers: ${esc(e.recipe.name)}</span><span class="m">${DAYS[e.day]} ${e.meal} · no extra cost</span></button>`).join('')}`:''}
      <div class="eyebrow" style="margin:8px 0 4px">Recipes</div>${rs.map(r=>`<button class="pick" data-choose="r:${r.id}" style="${fit(r)?'':'opacity:.7'}"><span class="rn">${r.favorite?'★ ':''}${esc(r.name)}</span><span class="m num">${r.minutes||'?'} min · ${r.nutrition?r.nutrition.kcal+' kcal · ':''}${money(recipeCost(r))}</span></button>`).join('')||'<div class="small faint">No recipe matches.</div>'}
      ${['snack','drink','treat','breakfast','lunch'].includes(meal)||ql?`<div class="eyebrow" style="margin:8px 0 4px">Regular items</div>${is.map(i=>`<button class="pick plain" data-choose="i:${i.id}"><span class="rn">${esc(i.name)}</span><span class="m">${esc(i.category)} · ${itemDue(i).due?'on the list':esc(itemDue(i).why.toLowerCase())}</span></button>`).join('')||'<div class="small faint">No regular items yet.</div>'}`:''}`};
  openModal(`${mhead(`${DAYS_LONG[day]} ${meal}`,'Choose a recipe, a regular item, or leftovers')}<div class="mb"><div class="search">${ICONS.search}<input id="pq" placeholder="Search"></div>
    <div><div class="eyebrow" style="margin-bottom:6px">Also add to</div><div class="daychecks">${DAYS.map((d,i)=>`<label ${i===day?'style="opacity:.5"':''}><input type="checkbox" data-day="${i}" ${i===day?'checked disabled':''}>${d}</label>`).join('')}</div></div>
    <div class="picker" id="pickList"></div></div>
    <div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn" data-action="create-chooser" data-day="${day}" data-meal="${meal}">${ICONS.plus} Create</button><button class="btn primary" data-action="disc-slot" data-day="${day}" data-meal="${meal}">${ICONS.search} Browse Discover</button></div></div>`);
  draw('');document.getElementById('pq').oninput=e=>draw(e.target.value);
  document.getElementById('pickList').onclick=e=>{const b=e.target.closest('[data-choose]');if(!b)return;const [t,id]=b.dataset.choose.split(':');const days=[...document.querySelectorAll('.daychecks input:checked')].map(x=>+x.dataset.day);
    for(const d of days){const entry=t==='r'?{t:'r',id,sv:S.settings.people||1}:t==='l'?{t:'l',of:id}:{t:'i',id};addEntry(d,meal,entry,!add&&d===day)}saveWeek();closeModal();toast(days.length>1?`Added to ${days.length} days`:'Added')}}

function openAddToPlan(id){const r=S.recipes[id];if(!r)return;const meals=activeMeals();const mon=parseISO(S.ui.weekKey);
  openModal(`${mhead('Add to plan',esc(r.name))}<div class="mb"><div class="small muted">Week of ${fmtDate(mon)} · tap a slot</div><div class="picker">${[...Array(7).keys()].map(d=>meals.map(m=>{const cur=slotEntries(week(),d,m);return `<button class="pick" data-slot="${d}|${m}"><span class="rn">${DAYS_LONG[d]} <span class="faint" style="font-family:var(--body);font-weight:500;font-size:13px">${m}</span></span><span class="m">${cur.length?cur.length+' planned':'free'}</span></button>`}).join('')).join('')}</div></div><div class="mf"><button class="btn ghost" data-close>Cancel</button></div>`);
  document.querySelector('.picker').onclick=e=>{const b=e.target.closest('[data-slot]');if(!b)return;const [d,m]=b.dataset.slot.split('|');addEntry(+d,m,{t:'r',id,sv:S.settings.people||1},false);saveWeek();closeModal();S.ui.tab='plan';render();toast('Added to '+DAYS_LONG[+d])}}

/* ---- log shop: see 9-discover-ui.js (openLogShop) ---- */
function markBought(line,date){for(const it of line.items){const cur=S.items[it.id];if(!cur)continue;cur.lastBought=date||iso(today());if(isMulti(cur)){const st=petStatus(cur);cur.remaining=Math.round((st.remaining+ +cur.packageSize)*100)/100;cur.remainingAsOf=iso(today())}else if(cur.frequency==='asneeded')cur.inStock=true;saveItem(cur)}}

/* ---- AI recipe import / generate ---- */
const RECIPE_SHAPE=()=>`Reply with only a JSON object of this exact shape:
{"name":string,"mealTypes":string[] (from: ${MEAL_TYPES.join(', ')}),"tags":string[] (from: ${TAGS.join(', ')}),"minutes":number,"servings":number,"ingredients":[{"qty":number,"unit":one of ${UNITS.filter(Boolean).map(u=>'"'+u+'"').join('|')} or "","name":string,"category":one of ${CATS.map(a=>'"'+a+'"').join('|')},"price":number (cost in ${S.settings.currency} of exactly this quantity, pro-rata of a pack)}],"steps":string[],"nutrition":{"kcal":number,"protein":number,"carbs":number,"fat":number} per single serving,"notes":string (leftover or storage tip, may be empty)}`;
function coerceRecipe(j){if(!j||typeof j!=='object'||!j.name)throw {code:'invalid_json'};
  const ings=Array.isArray(j.ingredients)?j.ingredients.map(i=>({qty:+i.qty||0,unit:UNITS.includes(i.unit)?i.unit:String(i.unit||''),name:String(i.name||'').trim(),category:CATS.includes(i.category)?i.category:guessCat(i.name),price:Math.round((+i.price||0)*100)/100})).filter(i=>i.name):[];const n=j.nutrition||{};
  const mt=Array.isArray(j.mealTypes)?j.mealTypes.filter(m=>MEAL_TYPES.includes(m)):[];
  return {id:uid(),name:String(j.name).trim(),mealTypes:mt.length?mt:['dinner'],tags:Array.isArray(j.tags)?j.tags.filter(t=>TAGS.includes(t)).slice(0,6):[],minutes:+j.minutes||30,servings:Math.max(1,Math.round(+j.servings||2)),ingredients:ings,steps:Array.isArray(j.steps)?j.steps.map(String):[],nutrition:{kcal:Math.round(+n.kcal||0),protein:Math.round(+n.protein||0),carbs:Math.round(+n.carbs||0),fat:Math.round(+n.fat||0)},nutritionEstimated:true,notes:String(j.notes||''),createdAt:Date.now()}}
function openAiRecipe(mode,slot){const isImport=mode==='import';
  openModal(`${mhead(isImport?'Import a recipe':'Generate a recipe',isImport?'Paste the text of any recipe. Claude turns it into a structured, priced card you review before saving.':'Describe what you fancy. Claude drafts a recipe with per-ingredient prices and nutrition for you to review.')}
    <div class="mb"><div class="field"><label for="aiIn">${isImport?'Recipe text':'What do you want?'}</label><textarea id="aiIn" style="min-height:${isImport?180:90}px" placeholder="${isImport?'Copy the ingredients and method from a website or your notes and paste here.':'e.g. a quick high-protein lunch I can prep for three days, or a cheap vegetarian dinner that makes good leftovers'}"></textarea></div>
    ${!isImport&&S.settings.diet?`<div class="small faint">Your preferences are included: “${esc(S.settings.diet.slice(0,140))}${S.settings.diet.length>140?'…':''}”</div>`:''}<div id="aiOut"></div></div>
    <div class="mf"><button class="btn ghost" data-close>Cancel</button><div class="actions"><button class="btn ghost" id="aiStop" hidden>Stop</button><button class="btn primary" id="aiGo">${ICONS.spark} ${isImport?'Structure it':'Draft recipe'}</button></div></div>`);
  let ctl=null;document.getElementById('aiStop').onclick=()=>ctl&&ctl.abort();
  document.getElementById('aiGo').onclick=async()=>{const txt=document.getElementById('aiIn').value.trim();if(!txt||!sampleFn)return;const out=document.getElementById('aiOut'),go=document.getElementById('aiGo'),stop=document.getElementById('aiStop');out.innerHTML='<div class="thinking"><span class="sp"></span>Thinking…</div>';go.disabled=true;stop.hidden=false;ctl=new AbortController();
    const B=budgetSummary();const prompt=isImport?`Convert this recipe text into structured data. Keep the author's ingredients and steps faithfully; normalise to metric (g, ml) where weights or volumes are given, otherwise use pcs. Estimate per-ingredient prices in ${S.settings.currency}${S.settings.store?' at '+S.settings.store:''} and nutrition per serving if not given.\n\n${RECIPE_SHAPE()}\n\nRECIPE TEXT:\n${txt.slice(0,20000)}`
      :`Create one home-cook recipe for ${S.settings.people} ${S.settings.people===1?'person':'people'}. Budget context: about ${money(B.availableForMeals)} is available for all planned recipes this week. Request: ${txt}\n${slot?`It is for ${MEAL_LABEL[slot.meal]}.\n`:''}${S.settings.diet?'Standing preferences: '+S.settings.diet+'\n':''}Use common supermarket ingredients, metric units, realistic quantities and a sensible servings count for leftovers.\n\n${RECIPE_SHAPE()}`;
    try{const j=await sampleFn.json(prompt,{signal:ctl.signal,cache:false});const r=coerceRecipe(j);if(slot&&!r.mealTypes.includes(slot.meal))r.mealTypes.push(slot.meal);closeModal();
      openEditor(r,{sub:'Review, then save',notice:isImport?'Structured by Claude from your text. Check quantities and prices before saving.':'Drafted by Claude. Prices and nutrition are estimates.',then:slot?saved=>{addEntry(slot.day,slot.meal,{t:'r',id:saved.id,sv:S.settings.people||1},true);saveWeek();S.ui.tab='plan';render()}:null})}
    catch(e){if(e&&e.code==='cancelled')out.innerHTML='';else out.innerHTML=`<div class="note bad">${aiErr(e)}</div>`}finally{go.disabled=false;stop.hidden=true}}}
